### ISSUE TITLE
Please update the .min.js

### ISSUE THREAD

**Issue by HartLarsson** [diegolamonica/EUCookieLaw3#10]
on https://diegolamonica.info/tools/eucookielaw3.min.js

there is a old version with many console.log() for debugging active:

![image](https://user-images.githubusercontent.com/16102074/41847472-650e17d4-787a-11e8-9dab-8635fe57e90f.png)

this version spams in console all user interactions 

Thanks

**Comment by diegolamonica** [comment]
New version is now available on the server!
Thanks for the feedback! :+1:
