### ISSUE TITLE
Ricarica pagina dopo accettazione/scroll - page reload after accepting - scrolling etc

### ISSUE THREAD

**Issue by luca7766** [diegolamonica/EUCookieLaw3#14]
Salve, da vecchio utilizzatore della vecchia versione, che prevedeva il reload della pagina web per far comparire gli elementi filtrati e bloccati da EUCookieLaw, mi chiedevo se anche con questa versione c'è la possibilità di effettuare un reload completo della pagina dopo scroll o accettazione tramite pulsante, ho cercato nella documentazione ma non ho trovato nulla a riguardo, mi dispiace disturbare qui, chiedo perchè ci sono java scripts (tipo finestre modali) che se bloccati non vengono eseguiti successivamente, e io non sono espertissimo nel campo, uso Joomla e ho inserito manualmente il codice necessario come da istruzioni.
Grazie mille, buon lavoro.

**Comment by diegolamonica** [comment]
Ciao @luca7766 secondo le linee guida sul GDPR, le direttive ePrivacy ed il garante, è necessario un consenso esplicito da parte dell'utente. 

*Lo scroll è considerato consenso implicito* poichè potresti arrivare ad una pagina (es. www.example.com) tramite un backlink che punta ad un'ancora che ne causerà lo scroll (es. www.example.com#footer ). Quindi, seppur contemplata questa funzionalità da EUCookieLaw3 ti sconsiglio di utilizzarla per evitare di incorrere in possibili sanzioni.

Premesso ciò, per eseguire il reload della pagina solo dopo l'accettazione o il rifiuto dei cookie fai riferimento alla sezione [Tracking consent and rejection (GDPR)](https://github.com/diegolamonica/EUCookieLaw3#tracking-consent-and-rejection-gdpr) della documentazione.

Fai attenzione che il metodo globale `userConsentCallback` descritto nella documentazione, viene invocato per ogni preferenza da parte dell'utente. Esso viene richiamato sia in caso di consenso che di dinniego. 
Pertanto, nell'implementazione più semplice dovresti tener traccia delle informazioni ricevute e capire se l'utente ha espresso la sua volontà per tutte le opzioni.

Ti riporto un esempio:
```javascript
{
   const consentStatus = {
      'gruppoA': null,
      'gruppoB': null,
      'gruppoC': null,
   }

    const hasAllConsents = () =>{
        return Object.keys(consentStatus)
            .every( item => (consentStatus[item] !== null) )  
    }

    window.userConsentCallback = function(groupName, agreementStatus, expressionDate){
        consentStatus[groupName] = agreementStatus;
        if( hasAllConsents() ) {
            window.location.reload();
        }
    }
}

```

**Comment by luca7766** [comment]
Grazie per la rapida risposta, dunque escludendo lo scrolling, c'è la possibilità di effettuare un reload della pagina dopo che l'utente ha premuto sul tasto di accettazione, e dopo aver settato o meno le impostazioni di blocco cookie (elementi permessi/non permessi)? Come appunto succedeva con la vecchia versione, dove vi erano parametri comodi da settare come:
reload: true,
agreeOnScroll: true,
agreeOnClick: true,

**Comment by diegolamonica** [comment]
Sì certo che puoi, usando il codice che ho riportato sopra (è un esempio, dovresti adattarlo alle tue necessità) se specifichi che la scelta viene registrata al click sul pulsante di chiusura, come descritto nella documentazione [proprietà agreeMethod](https://github.com/diegolamonica/EUCookieLaw3#agreemethod).
