### ISSUE TITLE
Disabilitare tasto ESC / Disable ESC keypress

### ISSUE THREAD

**Issue by luca7766** [diegolamonica/EUCookieLaw3#15]
Buondì, testando ancora questo ottimo script mi sono accorto che premendo il tasto ESC, la finestra/banner modale viene chiusa, esiste un modo per disabilitare il tasto ESC o altri tasti che potrebbero interferire? In modo che l'utente debba cliccare sui pulsanti del banner per confermare le scelte? Presumo sia una cosa legata a JQuery perchè ho notato che sul tuo sito personale (.info) non avviene tale fatto.

aggiungendo: data-keyboard="false" alla tag div della riga nel file js:
`html: '<div data-eucookielaw-id="{{id}}" id="eucookielaw-{{instanceId}}" class="modal fade eucookielaw-modal {{classes}}" **data-keyboard="false"** role="dialog" tabindex="-1">{{content}}</div>',`

sembra funzionare, sarebbe interessante implementare la funziona in maniera più user-friendly.

Sono in test con Joomla e framework Astroid (conflitto di stili ma se necessario aprirò un "ticket" nell'area apposita).

**Comment by diegolamonica** [comment]
È una funzionalità documentata che puoi ottenere usando il metodo `updateDialogProperty( id, propertyName, value)` come indicato di seguito:

```javascript
cookieLaw.updateDialogProperty( 
    'dialog-container', 
    'html', 
    '<div data-eucookielaw-id="{{id}}" id="eucookielaw-{{instanceId}}" class="modal fade eucookielaw-modal {{classes}}" data-keyboard="false" role="dialog" tabindex="-1">{{content}}</div>'
   );
```
