### ISSUE TITLE
Link per richiamare la finestra modale

### ISSUE THREAD

**Issue by luca7766** [diegolamonica/EUCookieLaw3#16]
Quando si usa il link proposto nella documentazione

```
<a href="#" onclick="cookieLaw.showAlert();" 
   class="btn btn-primary">Change your choices</a>

```
Su alcuni siti rimanda alla home page o comunque non funziona a dovere, testando invece, con:

```
<a href="javascript:void(0)" onclick="cookieLaw.showAlert();" 
   class="btn btn-primary">Change your choices</a>
```

Sembra non ci siano problemi, è corretto?

**Comment by diegolamonica** [comment]
Ciao @luca7766 dipende se c'è qualche javascript che interpreta l'ancora `#` come un ritorno alla home. Di norma questa forma rimanda in testa alla pagina corrente. 

La seconda forma è comunque corretta e lascia la pagina nella posizione attuale.

Tutto dipende dal comportamento che si vuole ottenere.
