### ISSUE TITLE
conflitto fra stili

### ISSUE THREAD

**Issue by uroboroprogetti** [diegolamonica/EUCookieLaw3#2]
Ciao e grazie ancora per il tuo prezioso lavoro;
ho purtroppo un problema con lo stile del banner; se nel codice includo le library di Bootstrap e JQuery il Banner viene visualizzato correttamente ma il tema del mio sito risulta leggermente alterato (dimensione dei font, rientri dei testi etc). Se invece non includo le library il banner non perde soltanto lo stile grafico ma anche la posizione, non risultando più fluttuante sopra la pagina ma fissato a fondo pagina sotto il footer. 
(n.b. fino a ieri l'avevo impostato con quest'ultima configurazione perché volevo mostrartelo, oggi invece ho cambiato con la configurazione che include le library e va in conflitto col CSS del mio tema, perché quel banner fissato sotto il footer era quasi invisibile)

**Comment by diegolamonica** [comment]
Spostata la issue nel repository corretto [Issue #2 - Themes](https://github.com/diegolamonica/EUCookieLaw3-themes/issues/2).
