### ISSUE TITLE
comportamento invertito?

### ISSUE THREAD

**Issue by uroboroprogetti** [diegolamonica/EUCookieLaw3#3]
il banner che ho configurato ora sembra avere un comportamento "invertito": cioè presenta la spunta verde su tutte le classi di cookie anche se l'impostazione è enabled: false

**Comment by diegolamonica** [comment]
La funzione di spunta verde sin dall'inizio è determinata dal metodo [`registerGroup( id, name, description, enabledByDefault)`](https://github.com/diegolamonica/EUCookieLaw3#registergroup-id-name-description-enabledbydefault) e non da `enabled: false`.

Se hai usato il configuratore, avrai abilitato per il singolo trattamento l'opzione riportata nell'immagine a seguire:

![image](https://user-images.githubusercontent.com/409514/40599649-73050fba-624e-11e8-859e-ec578edaea08.png)

**Comment by uroboroprogetti** [comment]
Grazie, la regione era proprio questa; non ho fatto caso a questa cosa nel configuratore perché avevo importato le impostazioni precedenti in cui l’opzione era disabilitata, devo aver fatto casino quando ho riordinato i box dei trattamenti.
Buona giornata

k
