### ISSUE TITLE
Wordfence considera pericoloso lo script di EuCookieLaw

### ISSUE THREAD

**Issue by mariobarretta** [diegolamonica/EUCookieLaw3#7]
Inserendo codice a seguire accade che Wordfence mi notifichi il seguente pericolo  :

403 Forbidden
A potentially unsafe operation has been detected in your request to this site, and has been blocked by Wordfence.

If you are an administrator and you are certain this is a false positive, you can automatically whitelist this request and repeat the same action.

  I am certain this is a false positive.

Whitelist This Action

Generated by Wordfence at Mon, 4 Jun 2018 9:59:00 GMT.
Your computer's time: Mon, 04 Jun 2018 09:59:01 GMT.

ecco il codice :  

<script src="https://marianicucine.it/wp-content/plugins/EUCookieLaw3-wp-master/scripts/eucookielaw3.min.js"></script>
<script type="text/javascript">
// <![CDATA[
// Generated with EUCookieLaw Configuration Builder on Mon Jun 04 2018
// Builder version 20180528.1

var cookieLaw = new EUCookieLaw({"agreeMethod":2,"cookieEnabled":false,"dialogCookieGroupsListDefaultIsHidden":true});

/* Dialog properties */
cookieLaw.updateDialogProperty("header-container", "content" ,"Informativa sull'uso dei cookie");
cookieLaw.updateDialogProperty("body-text-content", "content" ,"In questo sito vengono utilizzati cookie di terze parti (prodotti da social networks e servizi Google) per offrire un'esperienza di navigazione migliore. Tali cookie, secondo la nuova normativa  <a href=\"http://www.garanteprivacy.it/regolamento/\">UE GDPR (UE) 2016/679</a> , sono bloccati fino al tuo consenso ma ciò potrebbe pregiudicare l a tua esperienza d'uso del sito. Per maggiori informazioni puoi consultare l' <a href=\"https://ilmuseoaiborghi.it/privacy/\">informativa estesa</a> oppure la nostra pagina dei  <a href=\"https://ilmuseoaiborghi.it/cookie/\">cookie</a>");
cookieLaw.updateDialogProperty("review-button", "content" ,"Guarda i consensi");
cookieLaw.updateDialogProperty("close-button", "content" ,"Ho finito");
/* Blocking rules */
/* facebook*/
cookieLaw.registerGroup( "facebook", "Facebook", "Facebook", false );
cookieLaw.registerURL( "facebook", [".facebook.net",".facebook.com",".facebook.it"]); 
/* google-adsense*/
cookieLaw.registerGroup( "google-adsense", "Google Adsense", "Google Ad Sense", false );
cookieLaw.registerURL( "google-adsense", [".googlesyndication.com/pagead/"]); 
/* google-analytics*/
cookieLaw.registerGroup( "google-analytics", "Google Analytics", "Google Analytics", false );
cookieLaw.registerURL( "google-analytics", [".google-analytics.com"]); 
/* google-fonts*/
cookieLaw.registerGroup( "google-fonts", "Google Fonts", "Google Fonts", false );
cookieLaw.registerURL( "google-fonts", [".fonts.googleapis.com"]); 
/* google-maps*/
cookieLaw.registerGroup( "google-maps", "Google Maps", "Google Maps", false );
cookieLaw.registerURL( "google-maps", [".maps.google.com",".maps.googleapis.com",".www.google.com/maps",".www.google.it/maps"]); 
/* google-doubleclick*/
cookieLaw.registerGroup( "google-doubleclick", "Google Doubleclick", "Google Doubleclick", false );
cookieLaw.registerURL( "google-doubleclick", [".doubleclick.net"]); 
/* instagram*/
cookieLaw.registerGroup( "instagram", "Instagram", "instagram", false );
cookieLaw.registerURL( "instagram", [".instagram.com",".cdninstagram.com"]); 
/* linkedin*/
cookieLaw.registerGroup( "linkedin", "LinkedIn", "Linkedin", false );
cookieLaw.registerURL( "linkedin", [".linkedin.com"]); 
/* pinterest*/
cookieLaw.registerGroup( "pinterest", "Pinterest", "Pinterest", false );
cookieLaw.registerURL( "pinterest", [".pinterest.com"]); 
/* twitter*/
cookieLaw.registerGroup( "twitter", "Twitter", "Twitter", false );
cookieLaw.registerURL( "twitter", [".twitter.com",".twitterfeed.com"]); 
/* vimeo*/
cookieLaw.registerGroup( "vimeo", "Vimeo", "Vimeo", false );
cookieLaw.registerURL( "vimeo", [".vimeo.com"]); 
/* youtube*/
cookieLaw.registerGroup( "youtube", "YouTube", "YouTube", false );
cookieLaw.registerURL( "youtube", [".youtube-nocookie.com",".youtube.com"]); 
cookieLaw.run();
/* Configuration info
/EUCookieLawID::
eyJhZ3JlZU1ldGhvZCI6MiwiY29va2llRW5hYmxlZCI6ZmFsc2UsImRpYWxvZ0Nv
b2tpZUdyb3Vwc0xpc3REZWZhdWx0SXNIaWRkZW4iOmZhbHNlLCJkaWFsb2dQcm9w
ZXJ0aWVzIjp7ImhlYWRlci1jb250YWluZXIvY29udGVudCI6IkluZm9ybWF0aXZh
IHN1bGwndXNvIGRlaSBjb29raWUiLCJib2R5LXRleHQtY29udGVudC9jb250ZW50
IjoiSW4gcXVlc3RvIHNpdG8gdmVuZ29ubyB1dGlsaXp6YXRpIGNvb2tpZSBkaSB0
ZXJ6ZSBwYXJ0aSAocHJvZG90dGkgZGEgc29jaWFsIG5ldHdvcmtzIGUgc2Vydml6
aSBHb29nbGUpIHBlciBvZmZyaXJlIHVuJ2VzcGVyaWVuemEgZGkgbmF2aWdhemlv
bmUgbWlnbGlvcmUuIFRhbGkgY29va2llLCBzZWNvbmRvIGxhIG51b3ZhIG5vcm1h
dGl2YSBHRFBSICAoVUUpIDIwMTYvNjc5LCBzb25vIGJsb2NjYXRpIGZpbm8gYWwg
dHVvIGNvbnNlbnNvIG1hIGNp8iBwb3RyZWJiZSBwcmVnaXVkaWNhcmUgbCBhIHR1
YSBlc3BlcmllbnphIGQndXNvIGRlbCBzaXRvLiBQZXIgbWFnZ2lvcmkgaW5mb3Jt
YXppb25pIHB1b2kgY29uc3VsdGFyZSBsJyA8YSBocmVmPVwiaHR0cHM6Ly9tYXJp
YW5pY3VjaW5lLml0L3ByaXZhY3kvXCI+aW5mb3JtYXRpdmEgZXN0ZXNhPC9hPiBv
cHB1cmUgbGEgbm9zdHJhIHBhZ2luYSBkZWkgIDxhIGhyZWY9XCJodHRwczovL21h
cmlhbmljdWNpbmUuaXQvY29va2llL1wiPmNvb2tpZTwvYT4iLCJyZXZpZXctYnV0
dG9uL2NvbnRlbnQiOiJHdWFyZGEgaSBjb25zZW5zaSIsImNsb3NlLWJ1dHRvbi9j
b250ZW50IjoiSG8gZmluaXRvIn0sImJsb2NrZWRHcm91cHMiOnsiRmFjZWJvb2si
OnsiZGVzY3JpcHRpb24iOiJGYWNlYm9va2siLCJlbmFibGVkQnlEZWZhdWx0Ijpm
YWxzZSwia2V5cyI6WyIuZmFjZWJvb2submV0IiwiLmZhY2Vib29rLmNvbSIsIi5m
YWNlYm9vay5pdCJdfSwiR29vZ2xlIEFkc2Vuc2UiOnsiZGVzY3JpcHRpb24iOiJH
b29nbGUgQWQgU2Vuc2UiLCJlbmFibGVkQnlEZWZhdWx0IjpmYWxzZSwia2V5cyI6
WyIuZ29vZ2xlc3luZGljYXRpb24uY29tL3BhZ2VhZC8iXX0sIkdvb2dsZSBBbmFs
eXRpY3MiOnsiZGVzY3JpcHRpb24iOiJHb29nbGUgQW5hbHl0aWNzIiwiZW5hYmxl
ZEJ5RGVmYXVsdCI6ZmFsc2UsImtleXMiOlsiLmdvb2dsZS1hbmFseXRpY3MuY29t
Il19LCJHb29nbGUgRm9udHMiOnsiZGVzY3JpcHRpb24iOiJHb29nbGUgRm9udHMi
LCJlbmFibGVkQnlEZWZhdWx0IjpmYWxzZSwia2V5cyI6WyIuZm9udHMuZ29vZ2xl
YXBpcy5jb20iXX0sIkdvb2dsZSBNYXBzIjp7ImRlc2NyaXB0aW9uIjoiR29vZ2xl
IE1hcHMiLCJlbmFibGVkQnlEZWZhdWx0IjpmYWxzZSwia2V5cyI6WyIubWFwcy5n
b29nbGUuY29tIiwiLm1hcHMuZ29vZ2xlYXBpcy5jb20iLCIud3d3Lmdvb2dsZS5j
b20vbWFwcyIsIi53d3cuZ29vZ2xlLml0L21hcHMiXX0sIkdvb2dsZSBEb3VibGVj
bGljayI6eyJkZXNjcmlwdGlvbiI6Ikdvb2dsZSBEb3VibGVjbGljayIsImVuYWJs
ZWRCeURlZmF1bHQiOmZhbHNlLCJrZXlzIjpbIi5kb3VibGVjbGljay5uZXQiXX0s
Ikluc3RhZ3JhbSI6eyJkZXNjcmlwdGlvbiI6Imluc3RhZ3JhbSIsImVuYWJsZWRC
eURlZmF1bHQiOmZhbHNlLCJrZXlzIjpbIi5pbnN0YWdyYW0uY29tIiwiLmNkbmlu
c3RhZ3JhbS5jb20iXX0sIkxpbmtlZEluIjp7ImRlc2NyaXB0aW9uIjoiTGlua2Vk
aW4iLCJlbmFibGVkQnlEZWZhdWx0IjpmYWxzZSwia2V5cyI6WyIubGlua2VkaW4u
Y29tIl19LCJQaW50ZXJlc3QiOnsiZGVzY3JpcHRpb24iOiJQaW50ZXJlc3QiLCJl
bmFibGVkQnlEZWZhdWx0IjpmYWxzZSwia2V5cyI6WyIucGludGVyZXN0LmNvbSJd
fSwiVHdpdHRlciI6eyJkZXNjcmlwdGlvbiI6IlR3aXR0ZXIiLCJlbmFibGVkQnlE
ZWZhdWx0IjpmYWxzZSwia2V5cyI6WyIudHdpdHRlci5jb20iLCIudHdpdHRlcmZl
ZWQuY29tIl19LCJWaW1lbyI6eyJkZXNjcmlwdGlvbiI6IlZpbWVvIiwiZW5hYmxl
ZEJ5RGVmYXVsdCI6ZmFsc2UsImtleXMiOlsiLnZpbWVvLmNvbSJdfSwiWW91VHVi
ZSI6eyJkZXNjcmlwdGlvbiI6IllvdVR1YmUiLCJlbmFibGVkQnlEZWZhdWx0Ijpm
YWxzZSwia2V5cyI6WyIueW91dHViZS1ub2Nvb2tpZS5jb20iLCIueW91dHViZS5j
b20iXX19fQ==
::EUCookieLawID/*/
//]]></script>

**Comment by diegolamonica** [comment]
@mariobarretta ti prego di segnalare problemi legati a WordPress nello spazio opportuno:[Issue di EUCookieLaw per WordPress](https://github.com/diegolamonica/EUCookieLaw3-wp/issues).

L'ho appena [ricreata io](https://github.com/diegolamonica/EUCookieLaw3-wp/issues/3) nell'altro repository
