### ISSUE TITLE
Rimozione consensi rilasciati

### ISSUE THREAD

**Issue by mariobarretta** [diegolamonica/EUCookieLaw3#8]
Buongiorno a tutti, 
Ho dovuto disattivare eucookielaw3 in un sito ed ora mi sorge una domanda relativa ai consensi attualmente rilasciati dai visitatori dato che ho circa 3000 utenti che hanno rilasciato i loro consensi e che sono salvati nella apposita sezione consens ( ora non più raggiungibile ma visibile nuovamente non appena riattivo il plug in ) 
Come posso fare a cancellare tutti questi consensi e far si che i visitatori non siano più "limitati" nella fruizione del sito? 
Non vedendo un'azione generale di cancellazione spero che non si debba rimuovere manualmente ogni consenso rilasciato. 
Grazie e buon lavoro a tutti.

**Comment by HartLarsson** [comment]
Please remove your request because you still reference to WP plugin version not the normal jquery HTML version

**Comment by mariobarretta** [comment]
Hi, sorry but i do not understand.
I need to remove all consents given and i've followed the guide to install and use the plug in so my problem is present from all these days :(

**Comment by diegolamonica** [comment]
Ciao @mariobarretta, come evidenzia @HartLarsson, la segnalazione che fai riguarda la versione [WordPress](https://github.com/diegolamonica/EUCookieLaw3-wp) non la versione JavaScript.

Ti consiglio di riaprire la [issue nell'altro repository](https://github.com/diegolamonica/EUCookieLaw3-wp/issues).
