### ISSUE TITLE
Legacy mode in console

### ISSUE THREAD

**Issue by HartLarsson** [diegolamonica/EUCookieLaw3#9]
I ocntinue to receive a legacy mode waring in console plus 2 row like:
![image](https://user-images.githubusercontent.com/16102074/41822652-61b0b5f6-77f3-11e8-81f1-4db51a68ce3c.png)

The popup works but how to remove legacy and other info?

**Comment by diegolamonica** [comment]
@HartLarsson, thanks for th feedback... This issue is solved with [the new bulder v 20180625.1](http://diegolamonica.info/tools/eucookielaw/builder/) available since now!
